### ISSUE TITLE
tags.scm not found for .tsx

### ISSUE THREAD

**Issue by prakhar1989** [cased/kit#13]
Hi folks, 

This looks like an awesome project! I was trying to generate a repo map on my react/tsx project but seems like [tags.scm for typescript](https://github.com/cased/kit/blob/main/queries/typescript/tags.scm) end up erroring out for TSX?

```
WARNING:kit.tree_sitter_symbol_extractor:[EXTRACT] No query or parser available for extension: .tsx
WARNING:kit.tree_sitter_symbol_extractor:get_query: tags.scm not found at /cased-kit/venv/lib/python3.13/queries/typescript/tags.scm
```

Thanks!

**Comment by philbritton** [comment]
same issue with pip installed kit there are no queries, what was the resolution here?

**Comment by tnm** [comment]
@philbritton I believe this issue has been fixed in latest!

**Comment by stuckinforloop** [comment]
I'm still facing this issue with the latest update. Following is the error message:
```
get_query: tags.scm not found at /Users/neel.modi/stuckinforloop/codewhisper/.venv/lib/python3.11/queries/python/tags.scm
[EXTRACT] No query or parser available for extension: .py
symbols: []
```

@tnm what's the fix. I'm installing the cased-kit dependency with uv and it's at latest v0.2.0

**Comment by tnm** [comment]
Should be fixed for good in v0.2.1, for all install types; and with additional tests. Thanks for the reports :bow:
